function motor_forces = ComputeMotorForces(Fc,Gc,km,d)

%-------------------------------------------------
% Inputs:
%   Fc: control force
%   Gc: 3x1 control moments vector
%   d: motor distance from center of gravity
%   km: control moment coefficient

% Outputs:
%   motor_forces: 4x1 vector of force generated by each motor
%-------------------------------------------------

control_force_moments = [Fc;Gc];

CM = [-1,-1,-1,-1;
     -d/sqrt(2),-d/sqrt(2),d/sqrt(2),d/sqrt(2);
      d/sqrt(2),-d/sqrt(2),-d/sqrt(2),d/sqrt(2);
      km,-km,km,-km];

motor_forces = CM^-1 * control_force_moments;

end